version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  
  dev:
    commands: 
      - npm install
    IntegrationTest:
      commands: 
        - npm run test
    Deploy:
      commands: 
        - npm run sls -- deploy -s $STAGE -r $REGION
    AcceptanceTest:
      commands:
        - npm run acceptance