
service: hello-world-jezd

provider:
  name: aws
  runtime: nodejs8
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:scan
      Resource:
        Fn::GetAtt:
          - restaurantsTable
          - Arn
    - Effect: Allow
      Action: execute-api:Invoke
      Resource: arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/*/GET/restaurants

plugins:
  - serverless-offline
  - serverless-pseudo-parameters

functions:
  hello:
    handler: src/handelrs/handler.hello

  get-index:
    handler: src/handlers/get-index.handler
    events:
      - http:
          path: /
          method: get
    environment:
      restaurants_api:
        Fn::Join:
          - ''
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}/restaurants"
      cognito_user_pool_id: us-east-1_cAYHcYQXC
      cognito_client_id: 5mqtvug4jekfnve17sm30p6vr4

  search-restaurants:
    handler: src/handlers/search-restaurants.handler
    events:
      - http:
          path: /restaurants/search
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/us-east-1_cAYHcYQXC
    environment:
      restaurants_table: restaurants-jezd

  restaurants:
    handler: src/handlers/get-restaurants.handler
    events:
    - http:
        path: /restaurants
        method: get
        authorizer: aws_iam
    environment:
      restaurants_table: restaurants-jezd

resources:
  Resources:
    restaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: restaurants-jezd
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
